# This is a basic workflow to help you get started with Actions

name: CI_Emscripten

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout repository
      uses: actions/checkout@v2   

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v8

    - name: print version
      run: |
        em++ --version

    - name: build
      run: |
        echo "00_openwin"
        cd docs/00_openwin
        em++ ../../examples_newgl_glfw/00_openwin/main.cpp -o index.js \
          -std=c++17 \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 
        cd ../../

        echo "01_drawrect"
        cd docs/01_drawrect
        em++  ../../examples_newgl_glfw/01_drawrect/main.cpp -o index.js \
          -std=c++17  -I"../../include"  \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 
        cd ../../

        echo "02_nav3d"
        cd docs/02_nav3d
        em++  ../../examples_newgl_glfw/02_nav3d/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 
        cd ../../

        echo "03_texture"
        cd docs/03_texture
        em++  ../../examples_newgl_glfw/03_texture/main.cpp -o index.js \
          -std=c++17 -I"../../include"  \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 
        cd ../../

        echo "04_render2texture"
        cd docs/04_render2texture
        em++  ../../examples_newgl_glfw/04_render2texture/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 
        cd ../../

        echo "05_offscreenprojection"
        cd docs/05_offscreenprojection
        em++  ../../examples_newgl_glfw/05_OffScreenProjection/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../

        echo "20_cad2d"
        cd docs/20_cad2d
        em++  ../../examples_newgl_glfw/20_cad2d/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../

        echo "30_cadmsh2d"
        cd docs/30_cadmsh2d
        em++  ../../examples_newgl_glfw/30_cadmsh2d/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../

        echo "40_femcloth"
        cd docs/40_femcloth
        em++  ../../examples_newgl_glfw/40_femcloth/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -O2 -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../

        echo "41_fem2d_poisson"
        cd docs/41_fem2d_poisson
        em++  ../../examples_newgl_glfw/41_fem2d_poisson/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../

        echo "42_fem2d_linearsolid"
        cd docs/42_fem2d_linearsolid
        em++  ../../examples_newgl_glfw/42_fem2d_linearsolid/main.cpp -o index.js \
          -std=c++17 -I"../../include" \
          -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1
        cd ../../
